config/routes.rb
Rails.application.routes.draw do
  root "pages#welcome"
  get "/portfolio", to: "portfolio#index", as: :portfolio
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def welcome
  end
end

app/controllers/portfolio_controller.rb
class PortfolioController < ApplicationController
  def index
    @projects = [
      {
        :name => "Bolt Network",
        :image => "https://i.ibb.co/Qjmx0DhR/bolt-network.png",
        :description => "An streaming service for watching your favorite movies on demand.",
      },
      {
        :name => "Bass Music",
        :image => "https://i.ibb.co/RkGtP9jk/bass-music.png",
        :description => "Bass Music is a music application that you can view and listen to your favorite music artists.",
      },
      {
        :name => "Threadly",
        :image => "https://i.ibb.co/qYcht5Pm/threadly.png",
        :description => "An messaging application for sharing and sending messages with friends.",
      },
      {
        :name => "Broadway",
        :image => "https://i.ibb.co/sdbQMkSY/broadway.png",
        :description => "Broadway is a website where you can view current plays and learn about our team.",
      },
      {
        :name => "Innovation Cloud",
        :image => "https://i.ibb.co/G4V9f2Pd/innovation-cloud.png",
        :description => "An idea sharing application that you can create ideas and share them with other people on the platform.",
      },
    ]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/portfolio_helper.rb
module PortfolioHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Portfolio</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-LN+7fdVzj6u52u30Kp6M/trliBMCMKTyK833zpbD+pXdCLuTusPj697FH4R/5mcr" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="wrapper">
      <%= render "partials/header" %>
      <%= yield %>
      <%= render "partials/footer" %>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/js/bootstrap.bundle.min.js" integrity="sha384-ndDqU0Gzau9qJ1lfW4pNLlhNTkCfHzAVBReH9diLvGRem5+R9g2FzA8ZGN954O5Q" crossorigin="anonymous"></script>
  </body>
</html>

app/views/pages/welcome.html.erb
<main class="welcome">
  <img src="https://i.ibb.co/SXxqYcGQ/task-manager.jpg" />
  <h2>Welcome To My Portfolio</h2>
  <p>Welcome to my web developer portfolio, where you can view examples of my work for future employment opportunities. This Portfolio will tell you all about me and what I can provide for future employers. This Portfolio has a form that you can fill out to contact me about future work employments. There are also links to GitHub, LinkedIn, Twitter Accounts below.
  </p>
  <a href="/portfolio" class="btn">View My Work</a>
</main>

app/views/partials/_footer.html.erb
<footer class="footer">
  <p>&copy; 2025 Nick Tooley </p>
  <div class="links">
    <p>GitHub</p>
    <p>LinkedIn</p>
    <p>Twitter</p>
  </div>
</footer>

app/views/partials/_header.html.erb
<header class="header">
  <h1>Nick Tooley</h1>
  <ul>
    <li><%= link_to "Home", root_path %></li>
    <li><%= link_to "My Projects", portfolio_path %></li>
    <li><a href="#">About Myself</a></li>
    <li><a href="#">Contact Me</a></li>
  </ul>
</header>

app/views/portfolio/index.html.erb
<main class="portfolio">
  <img class="best" src="https://i.ibb.co/RkGtP9jk/bass-music.png" />
  <div class="content">
    <h2>My Projects</h2>
    <div class="projects">
      <% @projects.each do |project| %>
        <div class="project">
          <%= image_tag project[:image] %>
          <h3><%= project[:name] %></h3>
          <p><%= project[:description] %></p>
        </div>
      <% end %>
    </div>
  </div>
</main>